parameters:
  session.storage.options:
    name: 'ILRWEB'
    gc_probability: 1
    gc_divisor: 100
    gc_maxlifetime: 200000
    cookie_lifetime: 2000000
    sid_length: 48
    sid_bits_per_character: 6
  persistent_visitor_parameters.options:
    cookie_domain: .ilr.cornell.edu
services:
  cache.backend.database:
    class: Drupal\Core\Cache\DatabaseBackendFactory
    arguments: ['@database.sqlite_cache', '@cache_tags.invalidator.checksum', '@settings']
    tags:
      - { name: backend_overridable }
  database.sqlite_cache:
    class: Drupal\Core\Database\Connection
    factory: Drupal\Core\Database\Database::getConnection
    arguments: [default, sqlite_cache]
