<?php

/**
 * @file
 * Contains hide_entity_field.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_form_alter().
 */
function hide_entity_field_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();

  if ($form_object instanceof Drupal\Core\Entity\ContentEntityForm) {
    \Drupal::service('hide_entity_field.manager')->alterEntityForm($form, $form_state, $form_object->getEntity());
  }
}

/**
 * Implements hook_preprocess_HOOK for field templates().
 */
function hide_entity_field_preprocess_field(&$variables) {
  \Drupal::service('hide_entity_field.manager')->hideField($variables);
}



/**
 * Implements hook_entity_view_alter().
 */
function hide_entity_field_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // \Drupal::service('hide_entity_field.manager')->hideFields($build, $entity, $display);
}
