<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webform_reference_category_select\Hook\WebformHooks;

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
#[LegacyHook]
function webform_reference_category_select_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  return \Drupal::service(WebformHooks::class)->fieldWidgetThirdPartySettingsForm($plugin, $field_definition, $form_mode, $form, $form_state);
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
#[LegacyHook]
function webform_reference_category_select_options_list_alter(array &$options, array $context) {
  \Drupal::service(WebformHooks::class)->alterOptionsList($options, $context);
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 */
#[LegacyHook]
function webform_reference_category_select_field_widget_settings_summary_alter(&$summary, $context) {
  \Drupal::service(WebformHooks::class)->fieldWidgetSettingsSummaryAlter($summary, $context);
}
