<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function collection_node_menu_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $form_object = $form_state->getFormObject();
  $node = $form_object->getEntity();
  $collections = [];
  $collection_menus = [];

  if ($node->bundle() !== 'page') {
    return;
  }

  // Update the menu settings for nodes in collections with menus. This allows
  // the menu settings to appear even if the menu ThirdPartySettings have not
  // been configured for this bundle.
  $collection_items = \Drupal::service('collection.content_manager')->getCollectionItemsForEntity($node);

  if (!empty($collection_items)) {
    foreach ($collection_items as $collection_item) {
      $collection_menus = [];

      if ($collection_item->isCanonical()) {
        $collections[] = $collection_item->collection->entity;
      }
    }
  }

  // Check query param here.
  $collection_storage = \Drupal::entityTypeManager()->getStorage('collection');
  if (($collection_id_from_param = \Drupal::request()->query->get('collection')) && ($collection_from_param = $collection_storage->load($collection_id_from_param))) {
    $collections[] = $collection_from_param;
  }

  foreach ($collections as $collection) {
    // Check to see if the collection has one or more menus in it.
    foreach ($collection->findItems('menu') as $collection_item_menu) {
      $collection_menu = $collection_item_menu->item->entity;
      $collection_menus[$collection_menu->id()] = $collection_menu;
    }
  }

  foreach ($collection_menus as $collection_menu_id => $collection_menu) {
    // Load the entity type config for the node.
    $type = $form_object->getEntity()->type->entity;
    $available_menus = $type->getThirdPartySetting('menu_ui', 'available_menus');

    // Check if the type can be added to the main menu, but not the
    // collection menu. Override it if so.
    if (in_array('main', $available_menus) && !in_array($collection_menu->id(), $available_menus)) {
      $available_menus = [$collection_menu->id()];
      $type->setThirdPartySetting('menu_ui', 'available_menus', $available_menus);
    }
  }
}
