<?php

/**
 * @file
 * Contains person.module.
 */

use Drupal\Core\EventSubscriber\MainContentViewSubscriber;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function person_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the person module.
    case 'help.page.person':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows creation and management non-user people and their personas.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 *
 * Provides a theme definition for persona entities.
 */
function person_theme($existing, $type, $theme, $path) {
  $theme = [
    'persona' => [
      'path' => $path . '/templates',
      'template'  => 'persona',
      'render element' => 'elements',
    ],
    'persona_edit_form' => [
      'render element' => 'form',
    ],
    'persona_name_list' => [
      'variables' => [
        'names' => [],
      ]
    ],
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function person_theme_suggestions_persona(array $variables) {
  $suggestions = [];
  $persona = $variables['elements']['#persona'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'persona__' . $sanitized_view_mode;
  $suggestions[] = 'persona__' . $persona->bundle();
  $suggestions[] = 'persona__' . $persona->bundle() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Prepares variables for templates.
 */
function template_preprocess_persona(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  // Add article ARIA role.
  $variables['attributes']['role'] = 'article';
  /** @var \Drupal\person\PersonaInterface $persona */
  $persona = $variables['elements']['#persona'];
  //make the persona available
  $variables['persona'] = $persona;
  //provide the label
  $variables['label'] = $persona->getDisplayName();
  //provide the alias if there is an existing persona.
  if ($persona->id()) {
    $variables['url'] = $persona->toUrl()->toString();
  }

  // Add a variable to determine if the current request is for a modal.
  $wrapper_format = \Drupal::request()->query->get(MainContentViewSubscriber::WRAPPER_FORMAT);
  $variables['modal'] = in_array($wrapper_format, ['drupal_ajax', 'drupal_modal', 'drupal_dialog']);
}

/**
 * Implements hook_token_info().
 */
function person_token_info() {
  $info = [];
  $info['tokens']['persona']['smart_display_name'] = [
    'name' => 'Smart display name',
    'description' => 'The display name of the persona, even if it has been altered by a hook.'
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function person_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type == 'persona' && !empty($data['persona'])) {
    $persona = $data['persona'];

    foreach ($tokens as $name => $token) {
      if ($name === 'smart_display_name') {
        $replacements[$token] = $persona->getDisplayName();
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function person_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  if ($entity_form['#entity_type'] == 'persona') {
    /** @var \Drupal\person\PersonaInterface $persona */
    $persona = $entity_form['#entity'];

    if ($persona->person->entity) {
      $admin_label_placeholder = $persona->person->entity->display_name->value . ' - ' . $persona->type->entity->label();
      $entity_form['admin_label']['widget'][0]['value']['#description'] = str_replace('Jane Doe - Department Staffer', $admin_label_placeholder, $entity_form['admin_label']['widget'][0]['value']['#description']);

      // Add placeholder text for inherited values from the person record.
      foreach ($persona->type->entity->getInheritedFieldNames() as $field_name) {
        if ($persona->$field_name->isEmpty()) {
          $entity_form[$field_name]['widget'][0]['value']['#placeholder'] = $persona->person->entity->$field_name->value;
        }
      }
    }
    else {
      $entity_form['field_first_name']['widget'][0]['value']['#required'] = TRUE;
      $entity_form['field_last_name']['widget'][0]['value']['#required'] = TRUE;
    }
  }
}
