collection.collection_type.*:
  type: config_entity
  label: 'Collection type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    allowed_collection_item_types:
      type: sequence
      label: 'Allowed collection item types'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    uuid:
      type: string

collection.collection_item_type.*:
  type: config_entity
  label: 'Collection item type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
