<?php

/**
 * @file
 * Contains simple_columns.module.
 */

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_ckeditor_css_alter().
 */
function simple_columns_ckeditor_css_alter(array &$css, Editor $editor) {
  $editor_settings = $editor->getSettings();

  foreach ($editor_settings['toolbar']['rows'] as $row) {
    $all_items = array_merge(...array_column($row, 'items'));

    if (in_array('SimpleColumns', $all_items)) {
      $css[] = \Drupal::service('extension.list.module')->getPath('simple_columns') . '/css/simplecolumns.css';
      $css[] = \Drupal::service('extension.list.module')->getPath('simple_columns') . '/css/simplecolumns-editor.css';
      return;
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function simple_columns_element_info_alter(array &$types) {
  if (isset($types['processed_text'])) {
    $types['processed_text']['#attached']['library'][] = 'simple_columns/simple_columns';
  }
}
