<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\collection\Entity\CollectionType;
use Drupal\pathauto\PathautoState;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;

/**
 * @file
 * Contains ilr_salesforce.module.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_salesforce_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  // Only display the Salesforce title and series if the title has a value.
  if ($node->bundle() === 'event_landing_page' && $node->hasField('field_sf_title')) {
    $form['field_sf_title']['#access'] = !empty($node->field_sf_title->value);
    $form['field_series_name']['#access'] = $form['field_sf_title']['#access'];
  }

  if ($node->bundle() !== 'class') {
    return;
  }

  $form['class_sessions'] = [
    '#type' => 'details',
    '#title' => 'Class sessions',
    '#open' => TRUE,
    '#weight' => 125,
  ];

  // Loop over the computed `sessions` base field.
  // @see ilr_entity_field_storage_info() and ilr_entity_bundle_field_info().
  foreach ($node->sessions as $class_session) {
    $form['class_sessions'][$class_session->entity->id()] = [
      '#type' => 'inline_entity_form',
      '#entity_type' => 'class_session',
      '#bundle' => 'class_session',
      '#default_value' => $class_session->entity,
      '#form_mode' => 'mini',
      '#save_entity' => TRUE,
      '#op' => 'edit',
      // '#prefix' => $class_session->entity->uuid(),
      '#suffix' => '<hr/>',
      // '#disabled' => TRUE,
    ];
  }

  // Set the bare minimum 'inline_entity_form' value to the form state. This is
  // required to add the proper submit handlers to the node add/edit form. See
  // inline_entity_form_form_alter() in inline_entity_form.module
  $form_state->set(['inline_entity_form'], []);

}

/**
 * Implements hook_webform_element_alter().
 *   Set the ga_client_id here instead of using the TouchpointHandler. We do
 *   this because the element might be used on forms that are not using the
 *   TouchpointHandler, and we'd still like to get the value.
 */
function ilr_salesforce_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (isset($element['#webform_submission']) || empty($element['#webform_key'])) {
    return;
  }

  if ($element['#webform_key'] === 'ga_client_id') {
    $analytics_session_manager = Drupal::service('ilr_analytics_session_manager');
    $element['#default_value'] = $analytics_session_manager->getClientId();
  }
}
