<?php

/**
 * @file
 * Contains collection_item_path.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\collection\Entity\CollectionItem;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_base_field_info().
 *
 * Adds the `path` base field definition to collection items.
 */
function collection_item_path_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'collection_item') {
    $fields['path'] = BaseFieldDefinition::create('path')
      ->setLabel(t('URL alias'))
      ->setDescription(t('The collection item URL alias.'))
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'path',
        'weight' => 12,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setComputed(TRUE);

    return $fields;
  }
}

/**
 * Implements hook_metatags_alter().
 *
 * Updates the canonical url if the metatags module is present.
 *
 * @todo Consider generalizing this if needed to work in cases where the
 * metatags module is not present.
 *
 * @param array $metatags The special meta tags to be added to the page.
 * @param array $context The context for the current meta tags being generated.
 *   Will contain the following: 'entity' - The entity being processed; passed
 *   by reference.
 */
function collection_item_path_metatags_alter(array &$metatags, array &$context) {
  if (isset($context['entity']) && $context['entity'] instanceof CollectionItem) {
    $metatags['canonical_url'] = $context['entity']->item->entity->toUrl('canonical', ['absolute' => TRUE])->toString();
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Modifies the url for links to non-canonical collection items. Since items now
 * have a path, this allows a content admin to visit the collection item itself.
 * Eventually, we might add something like `$row['#entity'] = $entity` to the
 * CollectionItemListBuilder to make this simpler.
 */
function collection_item_path_form_collection_item_list_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entity_type_manager = \Drupal::service('entity_type.manager');
  $collection_item_storage = $entity_type_manager->getStorage('collection_item');

  foreach ($form['entities'] as $key => &$row) {
    if (!is_numeric($key) || !is_array($row)) {
      continue;
    }

    if ($collection_item = $collection_item_storage->load($key)) {

      if (!$collection_item->item->entity instanceof ContentEntityInterface || $collection_item->isCanonical()) {
        continue;
      }

      $row['item'] = [
        '#type' => 'link',
        '#title' => $collection_item->item->entity->label(),
        '#url' => $collection_item->toURL(),
        '#attributes' => [
          'class' => ['collection-item-entity-label'],
        ],
      ];
    }
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * Prepare the row to be modified if the collection item is not canonical.
 */
function collection_item_path_views_pre_render(ViewExecutable $view) {
  if (array_key_exists('collection_item', $view->getBaseTables())) {
    foreach($view->result as $row) {
      if ($row->_entity instanceof CollectionItem && $row->_entity instanceof ContentEntityInterface) {
        $row->collection_item_link = !$row->_entity->isCanonical();
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_view_field().
 *
 * Check for the collection_item_link value, and update the output of the
 * item__target_id field so it points to the collection item if found.
 * @see collection_item_path_views_pre_render().
 */
function collection_item_path_preprocess_views_view_field(&$variables) {
  if (empty($variables['row']->collection_item_link)) {
    return;
  }

  if ($variables['field']->realField === 'item__target_id') {
    $variables['output'] = $variables['row']->_entity->toLink();
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Update the tab title when viewing a collection item, to make it easier to
 * distinguish between editing the content of the item, and editin the item
 * itself. @see collection_item_path.links.task.yml
 */

function collection_item_path_menu_local_tasks_alter(&$data, $route_name) {
  if ($route_name !== 'entity.collection_item.canonical') {
    return;
  }

  if (isset($data['tabs'][0]['entity.collection_item.edit_form'])) {
    $data['tabs'][0]['entity.collection_item.edit_form']['#link']['title'] = t('Edit item');
  }
}

/**
 * Implements hook_node_view_alter().
 *
 * Sets the collection_item_url for non-canonical collection items.
 */
function collection_item_path_node_view_alter(array &$build) {
  if (isset($build['#collection_item']) && !$build['#collection_item']->isCanonical()) {
    $build['#node']->collection_item_url = $build['#collection_item']->toUrl();
  }
}

/**
 * Implements hook_taxonomy_term_view_alter().
 *
 * Sets the collection_item_url for extra fields rendered. Note that this looks
 * for a `collection_item` key in the render array. We may want to improve this,
 * possibly by looking for the `#collection_listing` key for all rendered
 * fields.
 */
function collection_item_path_taxonomy_term_view_alter(array &$build) {
  $rendered_collection_items = preg_grep('/^collection_item/', array_keys($build));

  if (empty($rendered_collection_items)) {
    return;
  }

  $collection_item_list = &$build[current($rendered_collection_items)];

  if (!isset($collection_item_list['#collection_listing'])) {
    return;
  }

  foreach ($collection_item_list['#items'] as &$item) {
    if ($item['#collection_item']->isCanonical()) {
      continue;
    }
    if (isset($item['#node'])) {
      $item['#node']->collection_item_url = $item['#collection_item']->toUrl();
    }
  }
}

/**
 * Link to the collection_item_url if it has been set.
 */
function collection_item_path_preprocess_node(&$variables) {
  if ($collection_item_url = $variables['node']->collection_item_url) {
    $variables['url'] = $collection_item_url;
  }
}
