<?php

/**
 * @file
 * Contains ilr_section_navigation.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\URL;

/**
 * Implements hook_entity_extra_field_info().
 */
function ilr_section_navigation_entity_extra_field_info() {
  $extra = [];

  // Add a pseudo-field that can display the computed section heading links on
  // blog collections. This will be exposed as a field block to layout builder.
  $extra['collection']['blog']['display']['ilr_section_navigation'] = [
    'label' => t('Section navigation (computed)'),
    'description' => t('This is a computed list of in page url fragment links to sections.'),
    'weight' => 0,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ilr_section_navigation_collection_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if (!$display->getComponent('ilr_section_navigation')) {
    return;
  }

  $links = [];

  foreach ($entity->field_sections as $section) {
    if ($section_link = $section->entity->getBehaviorSetting('in_page_nav', 'title')) {
      $behavior = $section->entity->type->entity->getBehaviorPlugin('in_page_nav');

      $links[] = [
        '#type' => 'link',
        '#title' => $section_link,
        '#url' => $entity->toUrl('canonical', ['fragment' => $behavior->getFragment($section->entity)]),
      ];
    }
  }

  if ($links) {
    $build['ilr_section_navigation'] = [
      '#theme' => 'item_list__section_navigation',
      '#title' => t('Explore'),
      '#items' => $links,
      '#attributes' => ['class' => 'section-navigation'],
      '#context' => ['collection' => $entity],
      '#cache' => [
        'tags' => $entity->getCacheTags(),
      ],
    ];
  }
}
