<?php

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_cron().
 */
function ilr_instagram_cron() {
  $last_purge = \Drupal::state()->get('ilr_instagram.last_purge', 0);

  // Clear instagram posts at least every hour.
  if ((\Drupal::time()->getRequestTime() - $last_purge) > (60 * 60)) {
    Cache::invalidateTags(['instagram_posts']);
    \Drupal::state()->set('ilr_instagram.last_purge', \Drupal::time()->getRequestTime());
  }
}
