<?php

/**
 * @file
 * Contains ilr_campaigns.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_help().
 */
function ilr_campaigns_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ilr_campaigns module.
    case 'help.page.ilr_campaigns':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage subscribers and campaigns over the CampaignMonitor API') . '</p>';
      return $output;

    default:
  }
}

/**
 *  Implements hook_theme_suggestions_html_alter().
 */
function ilr_campaigns_theme_suggestions_html_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'html__' . $node->bundle() . '__' . $node->view_mode;
  }
}

/**
 * Implements hook_ENTITY_insert().
 */
function ilr_campaigns_node_insert(ContentEntityInterface $node) {
  if ($node->bundle() === 'class') {
    $course_notifications_helper = \Drupal::service('ilr_campaigns.course_notifications');
    $course_notifications_helper->processNewClass($node);
  }
}

/**
 * Implements hook_cron().
 */
function ilr_campaigns_cron() {
  // @todo Maybe don't run this EVERY cron.
  $course_notifications_helper = \Drupal::service('ilr_campaigns.course_notifications');
  $course_notifications_helper->addCustomFieldOptions();
}
