<?php

/**
 * @file
 * Contains ilr.module.
 */
use Drupal\node\NodeForm;
use Drupal\user\Entity\User;
use Drupal\address\Plugin\Field\FieldWidget\AddressDefaultWidget;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\ilr\FieldStorageDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Field\FieldDefinition;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\WidgetBase;
use Drupal\Core\Cache\Cache;
use Drupal\webform\Plugin\WebformHandlerInterface;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\pathauto\PathautoPatternInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\taxonomy\VocabularyInterface;
use Drupal\collection\Entity\CollectionItemInterface;
use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Link;
use Drupal\ilr\Entity\CertificateNode;
use Drupal\ilr\Entity\ClassNode;
use Drupal\ilr\Entity\EventLandingNode;
use Drupal\ilr\Entity\EventNodeBase;
use Drupal\ilr\Entity\EventNodeInterface;
use Drupal\ilr\Entity\ImageMedia;
use Drupal\ilr\Hook\IlrHooks;
use Drupal\node\NodeInterface;
use Drupal\person\PersonaInterface;
use Drupal\salesforce_mapping\Entity\MappedObjectInterface;

/**
 * Implements hook_theme().
 */
function ilr_theme($existing, $type, $theme, $path) {
  return [
    'ilr_certificate_basics_block' => [
      'variables' => [
        'node' => [],
        'required_courses_text' => '',
        'completion_time' => '',
      ],
    ],
    'ilr_class_register_block' => [
      'variables' => [
        'classes' => [],
      ],
    ],
    'ilr_course_instructors_block' => [
      'variables' => [
        'label' => '',
        'instructors' => [],
      ],
    ],
    'ilr_course_instructor' => [
      'variables' => [
        'name' => '',
        'title' => '',
        'img' => '',
        'class_dates' => [],
        'class_ids' => [],
        'instructor_id' => '',
        'url' => ''
      ],
    ],
    'ilr_course_certificates_block' => [
      'variables' => [
        'node' => [],
        'certificates' => [],
      ],
    ],
    'ilr_course_page_nav_block' => [
      'variables' => [
        'node' => [],
        'links' => [],
      ],
    ],
    'ilr_event_when_where' => [
      'variables' => [
        'event_date' => [],
        'event_time' => [],
        'location_address' => [],
        'location_link' => [],
      ],
    ],
    'localist_event' => [
      'variables' => [
        'event' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function ilr_page_attachments(array &$attachments) {
  // Attach the webform datalayer library to every page.
  $attachments['#attached']['library'][] = 'ilr/ilr_webform_datalayer';
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Prepares variables for ilr_course_instructor templates.
 */
function template_preprocess_ilr_course_instructor(&$variables) {
  $variables['attributes']['data-classid'] = implode(' ', $variables['class_ids']);
  $variables['attributes']['data-instructorid'] = $variables['instructor_id'];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ilr_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['media']['image'])) {
    $bundles['media']['image']['class'] = ImageMedia::class;
  }

  if (isset($bundles['node']['class'])) {
    $bundles['node']['class']['class'] = ClassNode::class;
  }

  if (isset($bundles['node']['certificate'])) {
    $bundles['node']['certificate']['class'] = CertificateNode::class;
  }

  if (isset($bundles['node']['event_landing_page'])) {
    $bundles['node']['event_landing_page']['class'] = EventLandingNode::class;
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function ilr_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'collection_item') {
    $fields['sticky'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Sticky at top of lists'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 16,
      ])
      ->setDisplayConfigurable('form', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_entity_field_storage_info().
 */
function ilr_entity_field_storage_info(EntityTypeInterface $entity_type) {
  $definitions = [];

  if ($entity_type->id() == 'node') {
    $definitions = EventNodeBase::bundleFieldDefinitions($entity_type, 'event_landing_page', []);

    $definitions['classes'] = FieldStorageDefinition::create('entity_reference')
      ->setName('classes')
      ->setLabel(t('Classes'))
      ->setRevisionable(FALSE)
      ->setCustomStorage(TRUE)
      ->setTargetEntityTypeId($entity_type->id());
    $definitions['certificates'] = FieldStorageDefinition::create('entity_reference')
      ->setName('certificates')
      ->setLabel(t('Certificates'))
      ->setRevisionable(FALSE)
      ->setCustomStorage(TRUE)
      ->setTargetEntityTypeId($entity_type->id());
    $definitions['sessions'] = FieldStorageDefinition::create('entity_reference')
      ->setName('sessions')
      ->setLabel(t('Sessions'))
      ->setRevisionable(FALSE)
      ->setCustomStorage(TRUE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setTargetEntityTypeId($entity_type->id())
      ->setSetting('target_type', 'class_session');
  }

  return $definitions;
}

/**
 * Implements hook_entity_bundle_field_info().
 *
 * - Add computed fields to course nodes.
 * - Refine the settings for the collection_item `item` field:
 *   - Allow `media` and `taxonomy_term` entities.
 *   - Restrict the bundles for all allowed entities.
 *   - @todo: Allow these settings to be configured per collection_item bundle
 *     via the UI.
 *  - Add computed fields to class nodes.
 */
function ilr_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() == 'node' && $bundle == 'course') {
    $custom_field_storage = ilr_entity_field_storage_info($entity_type);

    $fields[$custom_field_storage['classes']->getName()] = FieldDefinition::createFromFieldStorageDefinition($custom_field_storage['classes']);

    $fields[$custom_field_storage['classes']->getName()]
      ->setLabel(t('Classes'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\ilr\CourseClassItemList')
      ->setSettings([
        'handler' => 'default:node',
        'handler_settings' => [
          'target_bundles' => [
            'class' => 'class'
          ]
        ],
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);

    $fields[$custom_field_storage['certificates']->getName()] = FieldDefinition::createFromFieldStorageDefinition($custom_field_storage['certificates']);

    $fields[$custom_field_storage['certificates']->getName()]
      ->setLabel(t('Certificates'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\ilr\CourseCertificateItemList')
      ->setSettings([
        'handler' => 'default:node',
        'handler_settings' => [
          'target_bundles' => [
            'certificate' => 'certificate'
          ]
        ],
      ])
      ->setDisplayConfigurable('view', FALSE);
  }

  if ($entity_type->id() == 'node' && $bundle == 'class') {
    $custom_field_storage = ilr_entity_field_storage_info($entity_type);

    $fields[$custom_field_storage['sessions']->getName()] = FieldDefinition::createFromFieldStorageDefinition($custom_field_storage['sessions']);

    $fields[$custom_field_storage['sessions']->getName()]
      ->setLabel(t('Sessions'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\ilr\ClassSessionItemList')
      ->setSettings([
        'handler' => 'default:class_session',
        'handler_settings' => [
          'target_bundles' => NULL,
        ],
      ]);
  }

  return $fields;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function ilr_entity_bundle_field_info_alter(array &$fields, EntityTypeInterface $entity_type, $bundle ) {
  foreach ($fields as $field_name => $field) {
    if ($field->getType() === 'link') {
      // Add a ProblemInternalLink constraint to link fields.
      $fields[$field_name]->addConstraint('ProblemInternalLink');
    }
  }

  // Add the UniqueMediaMentionExternalLink constraint to the media mention link field.
  if (($entity_type->id() === 'node') && ($bundle === 'media_mention')) {
    if (isset($fields['field_external_link'])) {
      $fields['field_external_link']->addConstraint('UniqueMediaMentionExternalLink');
    }
  }

  // Add the EventRegistrationSingleMethod constraint to the event landing page
  // registration URL field.
  if (($entity_type->id() === 'node') && ($bundle === 'event_landing_page')) {
    if (isset($fields['field_url'])) {
      $fields['field_url']->addConstraint('EventRegistrationSingleMethod');
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function ilr_entity_extra_field_info() {
  $extra = [];

  // Add a pseudo-field that can display the computed certificates field on this
  // course node. This will be exposed as a field block to layout builder.
  $extra['node']['course']['display']['ilr_certificates'] = [
    'label' => t('Certificates (computed)'),
    'description' => t('This is a computed backreference to certificates.'),
    'weight' => 0,
    'visible' => TRUE,
  ];

  // Add a pseudo-field that can display the course page links.
  $extra['node']['course']['display']['ilr_course_page_links'] = [
    'label' => t('Course Page Links (extra)'),
    'description' => t('A list of course page links.'),
    'weight' => 0,
    'visible' => TRUE,
  ];

  $extra['node']['media_mention']['display']['media_outlet_logo'] = [
    'label' => t('Media outlet logo'),
    'description' => t('The associated logo media entity image field.'),
    'weight' => 0,
    'visible' => TRUE,
  ];

  $extra['node']['media_mention']['display']['media_outlet_name'] = [
    'label' => t('Media outlet name'),
    'description' => t('The associated logo media entity name field.'),
    'weight' => 0,
    'visible' => FALSE,
  ];

  // Add extra fields to eventilicious node types, e.g. any node bundle with a
  // bundle class that extends EventNodeBase.
  foreach (\Drupal::service('entity_type.bundle.info')->getBundleInfo('node') as $bundle => $bundle_info) {
    if (isset($bundle_info['class'])) {
      $class = new ReflectionClass($bundle_info['class']);

      if ($class->isSubclassOf('\Drupal\ilr\Entity\EventNodeBase')) {
        $extra['node'][$bundle]['display']['event_when_where'] = [
          'label' => t('When & Where'),
          'description' => t('A combination of the event dates and location.'),
          'weight' => 0,
          'visible' => TRUE,
        ];
      }
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function ilr_entity_view_mode_alter(&$view_mode, EntityInterface $entity) {
  if ($view_mode === 'full' && $entity instanceof ContentEntityInterface && $entity->hasField('behavior_alt_display') && $entity->behavior_alt_display->value) {
    $view_mode = 'alt';
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ilr_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('ilr_certificates') && $view_mode === 'full') {
    $build['ilr_certificates'] = [
      '#theme' => 'ilr_course_certificates_block',
      '#node' => $entity,
      '#certificates' => $entity->certificates->referencedEntities(),
    ];
  }

  if ($display->getComponent('ilr_course_page_links') && $view_mode === 'full') {
    $page_links = [
      [
        'url' => '#course-details',
        'text' => 'Course Details',
      ],
      [
        'url' => '#instructors',
        'text' => 'The Instructors',
      ],
      [
        'url' => '#related-courses',
        'text' => 'Related Courses',
      ],
      [
        'url' => '/programs/professional-programs/registration-information',
        'text' => 'Registration Information',
      ]
    ];

    if ($entity->classes->count() === 0) {
      // Remove the instructors link when there are no classes.
      unset($page_links[1]);
    }

    $build['ilr_course_page_links'] = [
      '#theme' => 'ilr_course_page_nav_block',
      '#node' => $entity,
      '#links' => $page_links,
    ];
  }

  if ($display->getComponent('event_when_where')) {
    $build['event_when_where'] = [
      '#theme' => 'ilr_event_when_where',
      '#event_date' => $entity->event_date->view([
        'label' => 'hidden',
        'type' => 'date_range_without_time',
        'settings' => [
          'timezone_override' => '',
          'one_day' => 'M j, Y',
          'one_month' => 'M j - {j}, Y',
          'several_months' => 'M j - {M} {j}, Y',
          'several_years' => 'M j, Y - {M} {j}, {Y}',
        ],
      ]),
      '#event_time' => $entity->event_date->view([
        'label' => 'hidden',
        'type' => 'date_range_without_time',
        'settings' => [
          'timezone_override' => '',
          'one_day' => 'g:i A - {g}:{i} {A} {T}',
          'one_month' => 'g:i A - {g}:{i} {A} {T}',
          'several_months' => 'g:i A - {g}:{i} {A} {T}',
          'several_years' => 'g:i A - {g}:{i} {A} {T}',
        ],
      ]),
      '#location_address' => !$entity->location_address->isEmpty() ? $entity->location_address->view([
        'label' => 'hidden',
        'type' => 'address_default',
      ]) : '',
      '#location_link' => !$entity->location_link->isEmpty() ? $entity->location_link->view([
        'label' => 'hidden',
        'type' => 'link',
      ]) : '',
    ];
  }

  if ($display->getComponent('media_outlet_logo') || $display->getComponent('media_outlet_name')) {
    $external_link_host = parse_url($entity->field_external_link->uri, PHP_URL_HOST);

    // Derive a media outlet logo host and domain name (e.g. `nytimes.com`,
    // `bloomberg.com`) from the link host. See https://regex101.com/r/XvagCu/7
    // to test this regex.
    if (preg_match('/^(?:[^\.]+\.)*([^\.]+\.[a-z]{2,4})$/U', $external_link_host, $matches)) {
      $host = $matches[0];
      $domain = $matches[1];

      // Find logo media entities with a host or domain name that matches.
      $entity_type_manager = \Drupal::service('entity_type.manager');
      $logos = $entity_type_manager->getStorage('media')->loadByProperties([
        'bundle' => 'logo',
        'field_website_domain_name' => [$host, $domain],
        'status' => 1,
      ]);

      // Sort the logos by the best match. For example, prefer
      // `money.usnews.com` over `usnews.com`.
      uasort($logos, function($a, $b) use ($host, $domain) {
        $a_val = $a->field_website_domain_name->value;
        $b_val = $b->field_website_domain_name->value;
        $a_weight = $a_val === $host ? 0 : ($a_val === $domain ? 1 : 2);
        $b_weight = $b_val === $host ? 0 : ($b_val === $domain ? 1 : 2);
        return $a_weight <=> $b_weight;
      });

      $logo = $logos ? reset($logos) : FALSE;
    }
  }

  if ($display->getComponent('media_outlet_logo')) {
    $build['media_outlet_logo'] = [
      '#cache' => [
        'tags' => ['media_list'],
      ],
    ];

    if (!empty($logo)) {
      $build['media_outlet_logo']['logo'] = $logo->field_media_image->view('default');
    }
  }

  if ($display->getComponent('media_outlet_name')) {
    $build['media_outlet_name'] = [
      '#cache' => [
        'tags' => ['media_list'],
      ],
    ];

    if (!empty($logo)) {
      $build['media_outlet_name'] = [
        '#type' => 'inline_template',
        '#template' => '<div class="cu-x-media-mention__outlet">{{name}}</div>',
        '#context' => ['name' => $logo->label()],
      ];
    }
  }

  if ($entity instanceof EventNodeInterface) {
    if ($entity->hasField('field_registration_form') && !$entity->field_registration_form->isEmpty()) {
      // Attach the js library.
      $build['#attached']['library'][] = 'ilr/registration_webform_widget_enhancement';

      if (preg_match("/^# CONFIG \(DO NOT DELETE\)(.*)\n?/m", $entity->field_registration_form->default_data, $matches)) {
        if ($config = json_decode($matches[1])) {
          // Pass the Drupal settings if config was found.
          $build['#attached']['drupalSettings']['event_registration_form_config'] = $config;
        }
      }
    }
  }
}

/**
 * Implements hook_condition_info_alter();
 *
 * Use the plugin class from the Context Path module for all request_path
 * conditions.
 *
 * This allows all Request Path conditions to contain individual exclusions.
 *
 * @see https://medium.com/@djphenaproxima/how-to-bend-drupal-8-plugins-to-your-nefarious-will-94da0c31f095
 */
function ilr_condition_info_alter(array &$definitions) {
  if (array_key_exists('request_path', $definitions) && array_key_exists('request_path_inclexcl', $definitions)) {
    $definitions['request_path']['class'] = $definitions['request_path_inclexcl']['class'];
    unset($definitions['request_path_inclexcl']);
  }
}

/**
 * Implements hook_entity_prepare_view().
 */
function ilr_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
  if (empty($entities)) {
    return;
  }

  // Use a default value for course `field_message` if empty. This means that
  // courses can either use the default message as defined in the custom block
  // _or_ override that value. They cannot disable the message completely.
  if ($entity_type_id === 'node') {
    foreach ($entities as $node) {
      if ($node->bundle() === 'course' && $node->field_message->isEmpty()) {
        $default_message_block = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', '280c1d2d-0456-45eb-84dc-d114c5e7b2fa');

        if ($default_message_block) {
          $node->field_message->value = $default_message_block->body->value;
          $node->field_message->format = $default_message_block->body->format;
        }
      }
    }
  }

  if ($entity_type_id === 'paragraph') {
    foreach ($entities as $paragraph) {
      $paragraph->include_button = TRUE; // You can do this!?
      $paragraph->cu_icon = [];

      // Use data values from existing content (if specified) in promos.
      if ($paragraph->bundle() === 'promo' && !$paragraph->field_content->isEmpty()) {
        $content = $paragraph->field_content->entity;

        if ($content->getEntityTypeId() === 'persona') {
          $heading = $content->getDisplayName();
          $body = $content->field_bio->summary;
          $media = $content->hasField('field_photo') ? $content->field_photo : NULL;
          $paragraph->cu_icon = [
            'title' => 'Persona',
            'label' => 'Spotlight',
            'icon' => 'student',
            'attributes' => ['class' => 'cu-icon--color-light'],
          ];
        }
        else {
          $heading = $content->label();
          $body = $content->body->summary;
          $media = $content->hasField('field_representative_image') ? $content->field_representative_image : NULL;
        }

        if ($paragraph->field_heading->isEmpty()) {
          $paragraph->field_heading->value = $heading;
        }

        if ($paragraph->field_body->isEmpty()) {
          $paragraph->field_body->value = $body;
        }

        if ($paragraph->field_media->isEmpty() && !$media->isEmpty()) {
          $paragraph->field_media->target_id = $media->target_id;
        }

        if ($paragraph->field_link->isEmpty()) {
          $paragraph->field_link = [
            'uri' => 'entity:' . $content->toUrl()->getInternalPath(),
            'title' => t('Read more about') . ' ' . $paragraph->field_heading->value,
          ];
          $paragraph->include_button = FALSE;
        }
      }

      if ($paragraph->bundle() === 'promo' && !$paragraph->field_media->isEmpty() && !$paragraph->field_suppress_media->isEmpty() && $paragraph->field_suppress_media->value) {
        $paragraph->field_media->removeItem(0);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Prevent access to paragraphs that reference unpublished content.
 */
function ilr_paragraph_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation === 'view' && $entity->hasField('field_content') && !$entity->field_content->isEmpty()) {
    return AccessResult::forbiddenIf(!$entity->field_content->entity->access('view', $account));
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_query_alter().
 *
 * De-dupe grouped queries during the same request.
 *
 * Queries can be tagged for de-duping by setting a query tag in a specific
 * colon-delimited format:
 *
 * `dedupe:ID_FIELD:GROUP_ID`
 *
 * For example, all post listings are grouped by their collection, so the dedupe
 * group for collection 2 would be:
 *
 * `dedupe:collection_item.id:collection_2`
 *
 * Every query with that same tag will be deduped during a given request.
 *
 * NOTE: This will alter the SelectQuery that is compiled from the EntityQuery
 * such as \Drupal\ilr\Plugin\paragraphs\Behavior\PostListing::preprocess().
 * There is a contrib module that allows the altering of EntityQuery:
 * https://www.drupal.org/project/entity_query_alter.
 */
function ilr_query_alter(AlterableInterface $query) {
  if ($query->hasTag('dedupe_clone') || empty($query->alterTags)) {
    return;
  }

  // Find the 'dedupe_group' and 'dedupe_id_field' for this query, if it has
  // one. `alterTags` is a protected property in QueryBase, but it seems we can
  // access it here anyway. Which is lucky for us!
  foreach (array_keys($query->alterTags) as $tag) {
    if (preg_match('/^dedupe:([^:]+):(.+)$/', $tag, $matches)) {
      $dedupe_group = $tag;
      $dedupe_id_field = $matches[1];
    }
  }

  if (empty($dedupe_group)) {
    return;
  }

  // Fetch previously returned ids.
  $cached_ids = &drupal_static(__FUNCTION__ . '_' . $dedupe_group, []);

  // Add a condition to filter out previously returned record ids. Since this
  // can be a SelectQuery transformed from and EntityQuery, we can't use a
  // condition field name like `id` as we would in an original query like the
  // one in PostListing::preprocess.
  if (!empty($cached_ids)) {
    $query->condition($dedupe_id_field, $cached_ids, 'NOT IN');
  }

  // Clone this query so we can execute it without interfering with the
  // original. Plus, tag it to prevent an endless loop of this hook.
  $clone = clone $query;
  $clone->addTag('dedupe_clone');

  // Pager queries have no fields, so we can't call fetchAllKeyed().
  if (empty($clone->getFields())) {
    return;
  }

  // Execute the clone and append the record ids from this query to the cache.
  $cached_ids = array_merge($cached_ids, $clone->execute()->fetchAllKeyed());
}

/**
 * Implements hook_query_TAG_alter().
 */
function ilr_query_collection_items_for_entity_alter(AlterableInterface $query) {
  // Sort collection items for entities, as listed on the Collections tab for a
  // content entity, and in the inline collection item forms.
  $query->orderBy('canonical', 'desc');
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 */
function ilr_taxonomy_term_create_access(AccountInterface $account, array $context, $entity_bundle) {
  $vocabulary_entity = \Drupal::service('entity_type.manager')->getStorage('taxonomy_vocabulary')->load($entity_bundle);

  // See if the vocabulary is in a collection owned by this user.
  $collection_items = \Drupal::service('collection.content_manager')->getCollectionItemsForEntity($vocabulary_entity, FALSE);

  foreach ($collection_items as $collection_item) {
    if ($collection_item->access('update', $account)) {
      return AccessResult::allowed();
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements template_preprocess_node().
 */
function ilr_preprocess_node__course__teaser(&$variables) {
  $variables['upcoming_classes'] = [];

  foreach ($variables['node']->classes as $upcoming_class) {
    $class_is_in_person = strpos(strtolower($upcoming_class->entity->field_delivery_method->value ?? ''), 'online') === FALSE;

    switch($upcoming_class->entity->field_delivery_method->value) {
      case 'Classroom':
        $computed_delivery_method = t('In-Person');
        break;
      case 'On Demand/Self Paced':
        $computed_delivery_method = t('Self-Paced Online');
        break;
      default:
        $computed_delivery_method = t('Live Online');
    }

    // @todo Future Drupal/PHP will not allow object properties to be added like this.
    $upcoming_class->entity->computed_delivery_method = $computed_delivery_method;
    $variables['upcoming_classes'][] = $upcoming_class->entity;
  }
}

/**
 * Implements template_preprocess_node().
 * @see node.html.twig
 */
function ilr_preprocess_node__page__alt(&$variables) {
  $variables['page'] = TRUE;
  $node = $variables['node'];

  if ($node->hasField('field_sections') && $first_section = $node->field_sections->first()->entity) {
    if ($first_section->getBehaviorSetting('union_section_settings', 'wide')) {
      $variables['attributes']['class'][] = 'node--wide';
    }
  }
}

/**
 * Implements template_preprocess_collection().
 */
function ilr_preprocess_collection__subsite_blog__alt(&$variables) {
  $variables['attributes']['class'][] = 'collection--view-mode-alt';
  $collection = $variables['collection'];

  if ($collection->hasField('field_sections') && $first_section = $collection->field_sections->first()->entity) {
    if ($first_section->getBehaviorSetting('union_section_settings', 'wide')) {
      $variables['attributes']['class'][] = 'collection--wide';
    }
  }
}

/**
 * Implements template_preprocess_collection().
 */
function ilr_preprocess_collection__content_section__alt(&$variables) {
  $variables['attributes']['class'][] = 'collection--view-mode-alt';
  $collection = $variables['collection'];

  if ($collection->hasField('field_sections') && $first_section = $collection->field_sections->first()->entity) {
    if ($first_section->getBehaviorSetting('union_section_settings', 'wide')) {
      $variables['attributes']['class'][] = 'collection--wide';
    }
  }
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * Add the paragraphs id as a data attribute.
 * @see ParagraphsHostEntity::host drush command.
 */
function ilr_preprocess_paragraph(&$variables) {
  $variables['attributes']['data-pid'][] = $variables['paragraph']->id();
}

/**
 * Implements hook_token_info().
 */
function ilr_token_info() {
  $info = [];
  $info['tokens']['paragraph']['parent_entity_label'] = [
    'name' => 'Parent Entity Label',
    'description' => 'The label of the paragraph parent entity.'
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function ilr_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if ($type == 'paragraph' && !empty($data['paragraph'])) {
    $host_entity = $data['paragraph']->getParentEntity();

    foreach ($tokens as $name => $token) {
      if ($name === 'parent_entity_label') {
        $replacements[$token] = $host_entity->label();
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_entity_type_alter().
 */
function ilr_entity_type_alter(array &$entity_types) {
  $entity_types['node']->addConstraint('NodeMenuLevel');
}

/**
 * Implements hook_node_access().
 */
function ilr_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $type_id = $node->bundle();

  if ($op === 'view' && $account->hasPermission('view any ' . $type_id . ' unpublished content', $account)) {
    return AccessResult::allowed()->cachePerPermissions();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ilr_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'certificate') {
    $certificate_total = 0;
    $certificate_topics = [];

    // Deduce the total cost and topic terms of the certificate from its courses
    // (and classes).
    foreach ($entity->field_course->referencedEntities() as $course) {
      // Since `classes` is a computed field, and it is sorted by upcoming class
      // dates, using `first()` will ensure that the next upcoming class will be
      // used for the course price.
      if ($course->classes->count()) {
        $certificate_total += $course->classes->first()->entity->field_price->value;
      }

      // Add all unique topics for each course to the topics for certificate.
      foreach ($course->field_topics->referencedEntities() as $topic) {
        if (!in_array($topic->id(), $certificate_topics)) {
          $certificate_topics[] = $topic->id();
        }
      }
    }

    $entity->set('field_total_cost', $certificate_total);
    $entity->set('field_topics', $certificate_topics);
  }

  if ($entity->bundle() === 'class' && !$entity->field_course->isEmpty()) {
    Cache::invalidateTags($entity->field_course->entity->getCacheTagsToInvalidate());
  }

  \Drupal::service(IlrHooks::class)->populateRepresentativeImage($entity);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
#[LegacyHook]
function ilr_node_insert(EntityInterface $entity) {
  \Drupal::service(IlrHooks::class)->missingRepresetativeImageNotice($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
#[LegacyHook]
function ilr_node_update(EntityInterface $entity) {
  \Drupal::service(IlrHooks::class)->missingRepresetativeImageNotice($entity);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ilr_taxonomy_term_presave(EntityInterface $entity) {
  // If this is a new topic, add some default page links to Certificates,
  // Programs, and Customized Programs.
  if ($entity->bundle() === 'topics' && $entity->isNew()) {
    $entity->set('field_page_links', [
      [
        'uri' => 'internal:#certificates',
        'title' => 'Certificates'
      ],
      [
        'uri' => 'internal:#programs',
        'title' => 'Programs'
      ],
      [
        'uri' => 'internal:/customized-programs',
        'title' => 'Customized Programs'
      ],
    ]);
  }

  // Automatically create a new revision since there is no UI.
  // @see https://www.drupal.org/project/drupal/issues/2936995
  $entity->setNewRevision(TRUE);
  $entity->setRevisionUserId(\Drupal::currentUser()->id());
}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function ilr_media_load(array $entities) {
  $entity_type_manager = \Drupal::service('entity_type.manager');
  $users = $entity_type_manager->getStorage('user')->getQuery()->accessCheck(TRUE)->execute();

  foreach ($entities as $entity) {
    if (!in_array($entity->uid->target_id, $users)) {
      $entity->uid = 1;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\salesforce_mapping\Entity\MappedObjectInterface $entity
 */
function ilr_salesforce_mapped_object_insert(MappedObjectInterface $entity) {
  // Add new CAHRS event landing pages to the CAHRS collection.
  if ($entity->getMapping()->id() === 'cahrs_event_node') {
    try {
      $collection_item = \Drupal::service('entity_type.manager')->getStorage('collection_item')->create([
        'type' => 'default',
        'collection' => 53,
        'canonical' => TRUE,
      ]);
      $collection_item->item = $entity->getMappedEntity();
      $collection_item->save();
    }
    catch (\Exception $e) {
      // Do nothing. This page is probably already in the collection. We don't
      // use $entity->getMappedEntity()->isNew() because by the time the
      // salesforce_mapped_object is saved, its mapped entity has already been
      // saved.
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['saml_login_title'] = [
    '#markup' => '<h2>' . t('Cornell Users') . '</h2>',
    '#weight' => -3
  ];

  $form['saml_login'] = [
    '#type' => 'link',
    '#url' => Url::fromRoute('samlauth.saml_controller_login'),
    '#title' => t('NetID Login'),
    '#weight' => -2,
    '#attributes' => [
      'class' => 'cu-button'
    ],
    '#attached' => [
      'library' => [
        'union_organizer/button'
      ]
    ]
  ];

  $form['drupal_login_container_open'] = [
    '#markup' => '<details><summary>' . t('No Cornell NetID?') . '</summary>',
    '#weight' => -1
  ];

  $form['drupal_login_container_close'] = [
    '#markup' => '</details><p></p>',
    '#weight' => 100
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add a new node add/edit form advance group section. This is generally shown
  // in the right-hand column.
  /** @see Drupal\node\NodeForm */
  $form['ilr_meta'] = [
    '#type' => 'details',
    '#title' => t('Meta'),
    '#group' => 'advanced',
    '#weight' => -10,
    '#optional' => TRUE,
    '#open' => TRUE,
  ];

  // Move representative image/video and page body fields into the new section.
  $form['field_representative_image']['#group'] = 'ilr_meta';
  $form['field_featured_media']['#group'] = 'ilr_meta';

  // Put inline collection item forms in the 'sidebar' on node add/edit forms.
  $form['ief_collection_items']['#group'] = 'advanced';

  if (!empty($form['field_representative_img_caption'])) {
    $form['field_representative_img_caption']['#group'] = 'ilr_meta';
  }

  $form['ilr_node_settings'] = [
    '#type' => 'details',
    '#title' => t('Custom settings'),
    '#group' => 'advanced',
    '#weight' => -9,
    '#optional' => TRUE,
    '#open' => FALSE,
  ];

  $form['auth_protected']['#group'] = 'ilr_node_settings';
  $form['behavior_alt_display']['#group'] = 'ilr_node_settings';
  $form['behavior_alt_display']['#access'] = \Drupal::currentUser()->hasPermission('set alternate display');
  $form['behavior_suppress_listing']['#group'] = 'ilr_node_settings';

  /** @var \Drupal\node\NodeForm $form_object */
  $form_object = $form_state->getFormObject();

  if ($form_object instanceof NodeForm) {
    $node = $form_object->getEntity();

    if ($node->bundle() === 'page' || $node->bundle() === 'story') {
      $form['body']['#group'] = 'ilr_meta';
    }

    if ($node->type->entity->getThirdPartySetting('extended_post', 'extends_posts')) {
      $form['body']['#group'] = 'ilr_meta';
      $form['field_authors']['#group'] = 'ilr_meta';
      $form['field_experts']['#group'] = 'ilr_meta';
      $form['field_published_date']['#group'] = 'ilr_meta';
      $form['author']['#title'] = t('Creation information');
      $form['uid']['widget'][0]['target_id']['#title'] = t('Created by');
      $form['created']['widget'][0]['value']['#title'] = t('Created on');
    }

    if ($node->bundle() === 'course') {
      $form['field_message']['#group'] = 'ilr_meta';
      $form['field_delivery_method']['#group'] = 'ilr_meta';
      $form['field_sponsor']['#group'] = 'ilr_meta';
      $form['field_topics']['#group'] = 'ilr_meta';
      $form['field_key_outcomes']['#group'] = 'ilr_meta';
      $form['field_target_audience']['#group'] = 'ilr_meta';
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_form_persona_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Move collection items into the advanced group.
  $form['ief_collection_items']['#group'] = 'advanced';

  // Move editors on ilr_employee personas to the meta section in the advanced
  // group, e.g. the sidebar of the add/edit form.
  if (strpos($form_id, 'persona_ilr_employee') === 0) {
    if (isset($form['field_editors'])) {
      $form['field_editors']['#group'] = 'meta';
    }

    $form['inherited']['#group'] = 'advanced';
    $form['inherited']['#weight'] = -9;

    if (!empty($form['imported_info'])) {
      $form['imported_info']['#description'] = t('Imported information can be modified in @workday_link.', [
        '@workday_link' => Link::fromTextAndUrl('Workday', Url::fromUri('https://shibidp.cit.cornell.edu/idp/profile/SAML2/Unsolicited/SSO?providerId=http://www.workday.com'))->toString(),
      ]);

      // Move the read-only list of related employee positions to the imported
      // info section.
      $form['extra_field_ilr_employee_positions_description']['#group'] = 'imported_info';

      $form['field_display_name_override']['#group'] = 'imported_info';
    }

    // Only show the display name override if the display_name is disabled.
    if (!isset($form['display_name']['#disabled']) || !$form['display_name']['#disabled']) {
      $form['field_display_name_override']['#access'] = FALSE;
    }
  }

  // @Add a tab for ULR Redirects.
  // @see redirect_form_node_form_alter().
  /** @var \Drupal\person\PersonaInterface $persona */
  $persona = $form_state->getFormObject()->getEntity();

  if (!$persona->isNew() && \Drupal::currentUser()->hasPermission('administer redirects')) {

    $pid = $persona->id();

    // Find redirects to this persona.
    $redirects = \Drupal::service('redirect.repository')
      ->findByDestinationUri(["internal:/persona/$pid", "entity:persona/$pid"]);

    // Assemble the rows for the table.
    $rows = [];
    /** @var \Drupal\Core\Entity\EntityListBuilder $list_builder */
    $list_builder = \Drupal::service('entity_type.manager')->getListBuilder('redirect');
    /** @var \Drupal\redirect\Entity\Redirect[] $redirects */
    foreach ($redirects as $redirect) {
      $row = [];
      $path = $redirect->getSourcePathWithQuery();
      $row['path'] = [
        'class' => ['redirect-table__path'],
        'data' => ['#plain_text' => $path],
        'title' => $path,
      ];
      $row['operations'] = [
        'data' => [
          '#type' => 'operations',
          '#links' => $list_builder->getOperations($redirect),
        ],
      ];
      $rows[] = $row;
    }

    // Add the list to the vertical tabs section of the form.
    $header = [
      ['class' => ['redirect-table__path'], 'data' => t('From')],
      ['class' => ['redirect-table__operations'], 'data' => t('Operations')],
    ];
    $form['url_redirects'] = [
      '#type' => 'details',
      '#title' => t('URL redirects'),
      '#group' => 'advanced',
      '#open' => FALSE,
      'table' => [
        '#type' => 'table',
        '#header' => $header,
        '#rows' => $rows,
        '#empty' => t('No URL redirects available.'),
        '#attributes' => ['class' => ['redirect-table']],
      ],
      '#attached' => [
        'library' => [
          'redirect/drupal.redirect.admin',
        ],
      ],
    ];

    if (!empty($rows)) {
      $form['url_redirects']['warning'] = [
        '#markup' => t('Note: links open in the current window.'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',
      ];
    }

    $form['url_redirects']['actions'] = [
      '#theme' => 'links',
      '#links' => [],
      '#attributes' => ['class' => ['action-links']],
    ];
    $form['url_redirects']['actions']['#links']['add'] = [
      'title' => t('Add URL redirect'),
      'url' => Url::fromRoute('redirect.add', [
        'redirect' => $persona->toUrl()->getInternalPath(),
        'destination' => \Drupal::destination()->get(),
      ]),
      'attributes' => [
        'class' => [
          'button',
        ],
        'target' => '_blank',
      ],
    ];
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function ilr_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if (isset($context['widget']) && $context['widget'] instanceof AddressDefaultWidget) {
    $element['#type'] = 'fieldset';
  }
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function ilr_field_widget_single_element_webform_entity_reference_select_form_alter(&$element, FormStateInterface &$form_state, $context) {
  $webform_options_storage = \Drupal::entityTypeManager()->getStorage('webform_options');
  $mapped_object_storage = \Drupal::entityTypeManager()->getStorage('salesforce_mapped_object');
  $cahrs_event_node_mapping = \Drupal::entityTypeManager()->getStorage('salesforce_mapping')->load('cahrs_event_node');
  $entity = $form_state->getFormObject()->getEntity();
  $default_data_value = $element['settings']['default_data']['#default_value'] ?? '';

  if (strpos($default_data_value, 'outreach_marketing_personas:') === FALSE) {
    return;
  }

  /** @var \Drupal\webform\Entity\WebformOptions $touchpoint_options */
  $touchpoint_options = $webform_options_storage->load('touchpoint_emps');
  $dummy_element = ['#options' => $touchpoint_options->id()];
  $emp_options = $touchpoint_options->getElementOptions($dummy_element);

  $element['settings']['helper_wrapper'] = [
    '#type' => 'details',
    '#title' => t('Marketing settings'),
    '#open' => FALSE,
  ];

  $element['settings']['helper_wrapper']['emps_helper'] = [
    '#type' => 'checkboxes',
    '#title' => t('Available <em>Email Marketing Personas</em>'),
    '#description' => t('Selecting EMPs here will update the <code>outreach_marketing_personas</code> value below.'),
    '#options' => $emp_options,
    '#attributes' => [
      'class' => ['emp-details'],
    ],
  ];

  if (!$entity->isNew()) {
    /** @var \Drupal\salesforce_mapping\Entity\MappedObjectInterface */
    $drupal_mapped_object = $mapped_object_storage->loadByEntityAndMapping($entity, $cahrs_event_node_mapping);

    // @todo See if this sf event ($drupal_mapped_object->sfid()) has Activity_Format__c == 'CAHRS Partner Meeting'
    if (!empty($drupal_mapped_object)) {
      $options = $webform_options_storage->load('cahrs_session_details')->getOptions();

      $element['settings']['cahrs'] = [
        '#type' => 'checkboxes',
        '#title' => t('Available <em>Optional activities</em> options'),
        '#description' => t('Select the allowed options for the <em>Optional activities</em> field for this CAHRS partner event.'),
        '#options' => $options,
        '#attributes' => [
          'class' => ['cahrs-session-details'],
        ],
      ];
    }
  }

  $element['settings']['default_data']['#weight'] = 1;
  $element['#attached']['library'][] = 'ilr/registration_webform_widget_enhancement';
}

/**
 * Implements hook_webform_options_WEBFORM_OPTIONS_ID_alter().
 *
 * Use the current date to dynamically update the graduation date options.
 */
function ilr_webform_options_undergraduate_application_date_alter(array &$options, array &$element) {
  $cid = 'ilr_undergraduate_application_date';

  if ($cache = \Drupal::cache()->get($cid)) {
    $options = $cache->data;
    return;
  }

  $current_year = idate('y');
  $next_year = $current_year + 1;

  // Jan - May
  if (idate('m') < 6) {
    $options = [
      "May '$current_year" => "May '$current_year",
      "Aug '$current_year" => "Aug '$current_year",
      "Dec '$current_year" => "Dec '$current_year",
    ];
  }
  // Jun - Aug
  elseif (idate('m') < 9) {
    $options = [
      "Aug '$current_year" => "Aug '$current_year",
      "Dec '$current_year" => "Dec '$current_year",
      "May '$next_year" => "May '$next_year",
    ];
  }
  // Sep - Dec
  else {
    $options = [
      "Dec '$current_year" => "Dec '$current_year",
      "May '$next_year" => "May '$next_year",
      "Aug '$next_year" => "Aug '$next_year",
    ];
  }

  // Cache these options for 24 hours.
  \Drupal::cache()->set($cid, $options, time() + 60 * 60 * 24);
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 *
 * @see ilr_field_widget_single_element_paragraphs_previewer_form_alter().
 */
function ilr_field_widget_single_element_paragraphs_form_alter(&$element, FormStateInterface &$form_state, $context) {
  $paragraphs_entity = NULL;
  $delta = $element['#delta'];
  $field_name = $context['items']->getName();
  $widget_state = WidgetBase::getWidgetState($element['#field_parents'], $field_name, $form_state);

  // Load the paragraph entity if possible.
  /** @see \Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget::formElement() */
  if (isset($widget_state['paragraphs'][$delta]['entity'])) {
    $paragraphs_entity = $widget_state['paragraphs'][$delta]['entity'];
  }
  elseif (isset($context['items'][$delta]->entity)) {
    $paragraphs_entity = $context['items'][$delta]->entity;
  }

  // Section paragraph types should show the heading as the label if the heading
  // has a value.
  if ($paragraphs_entity && $paragraphs_entity->bundle() === 'section') {
    if ($heading = $paragraphs_entity->field_heading->value) {
      $element['top']['type']['label']['#markup'] = '<span class="paragraph-type-label">' . $heading . '</span>';
    }
    else {
      $admin_label = $paragraphs_entity->getBehaviorSetting('admin_section_label', 'label') ?? t('Section');
      $element['top']['type']['label']['#markup'] = '<span class="paragraph-type-label paragraph-type-label--admin-label">' . $admin_label . '</span>';
    }

    // Automatically set the section heading to the left for new sections on
    // event landing pages.
    if ($paragraphs_entity->isNew() && $host_entity = $paragraphs_entity->getParentEntity()) {
      if ($host_entity->bundle() === 'event_landing_page') {
        $element['behavior_plugins']['union_section_settings']['heading_left']['#default_value'] = TRUE;
      }
    }
  }

  // Hide the subheading and subheading link on section paragraphs until the
  // heading has a value.
  if ($paragraphs_entity && $paragraphs_entity->bundle() === 'section' && isset($element['subform']['field_heading'])) {
    $selector = sprintf(':input[name="%s[%d][subform][field_heading][0][value]"]', $field_name, $delta);
    $element['subform']['field_subheading']['#states'] = [
      'invisible' => [
        $selector => ['value' => ''],
      ],
    ];
    $element['subform']['field_subheading_link']['#states'] = [
      'invisible' => [
        $selector => ['value' => ''],
      ],
    ];

    // Change the the subheading link field to a details element so it will be
    // collapsed by default.
    $element['subform']['field_subheading_link']['widget'][0]['#type'] = 'details';
  }

  // Remove the weight value from the behavior_plugins element to help detect if
  // it's empty.
  unset($element['behavior_plugins']['#weight']);

  // Wrap behavior settings elements in a details container.
  if (!empty($element['behavior_plugins'])) {
    $element['behavior_plugins']['#type'] = 'details';
    $element['behavior_plugins']['#title'] = t('@type Settings', [
      '@type' => $paragraphs_entity->type->entity->label(),
    ]);
    $element['behavior_plugins']['#weight'] = -99;

    // Check if there are any fields added by the UI to this paragraph.
    $behavior_driven_component = empty(array_filter(array_keys($paragraphs_entity->getFields()), function($key) {
      return strpos($key, 'field_') === 0;
    }));

    // If it's behavior-driven, leave the element open.
    $element['behavior_plugins']['#open'] = $behavior_driven_component || in_array($paragraphs_entity->bundle(), ['publications']);
  }

  // Add a class to closed paragraphs.
  $element['#attributes']['class'] = ['js-paragraph-mode--' . ($widget_state['paragraphs'][$delta]['mode'] ?? 'missing')];

  // If it's a promo, combine relevant fields in a details box for existing
  // content.
  if ($paragraphs_entity && $paragraphs_entity->bundle() === 'promo') {
    if (isset($element['subform']['field_content'])) {
      $group_selector = implode('][', array_merge($element['subform']['#parents'], ['ilr_content_wrapper']));

      $element['subform']['ilr_content_wrapper'] = [
        '#type' => 'details',
        '#title' => $element['subform']['field_content']['widget'][0]['#title'],
        '#weight' => $element['subform']['field_content']['#weight'],
        '#open' => !$paragraphs_entity->field_content->isEmpty(),
      ];

      $element['subform']['field_content']['widget'][0]['#type'] = 'container';
      $element['subform']['field_content']['#group'] = $group_selector;
      $element['subform']['field_suppress_media']['#group'] = $group_selector;
    }

    // Collapse the button (link) field if there is no value.
    if (isset($element['subform']['field_link'])) {
      $element['subform']['field_link']['widget'][0]['#type'] = 'details';
      $element['subform']['field_link']['widget'][0]['#open'] = !$paragraphs_entity->field_link->isEmpty();
    }
  }
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function ilr_field_widget_single_element_paragraphs_previewer_form_alter(&$element, FormStateInterface &$form_state, $context) {
  ilr_field_widget_single_element_paragraphs_form_alter($element, $form_state, $context);
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function ilr_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  if ($field_definition->getType() === 'text_with_summary') {
    $element = [];

    $element['hide_value'] = [
      '#type' => 'checkbox',
      '#title' => t('Hide the main text input field'),
      '#description' => t('Only useful when the summary field is displayed.'),
      '#default_value' => $plugin->getThirdPartySetting('ilr', 'hide_value'),
    ];

    // The summary description only appears if the summary is not required.
    if (!$field_definition->getSetting('required_summary')) {
      $element['hide_summary_description'] = [
        '#type' => 'checkbox',
        '#title' => t('Hide the summary description'),
        '#default_value' => $plugin->getThirdPartySetting('ilr', 'hide_summary_description'),
      ];
    }

    return $element;
  }
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function ilr_field_widget_single_element_text_textarea_with_summary_form_alter(&$element, FormStateInterface $form_state, $context) {
  $widget = $context['widget'];

  // We can't use the protected isDefaultValueWidget() method.
  if ((bool) $form_state->get('default_value_widget')) {
    return;
  }

  if ($widget->getThirdPartySetting('ilr', 'hide_summary_description')) {
    unset($element['summary']['#description']);
  }

  if ($widget->getThirdPartySetting('ilr', 'hide_value')) {
    $element['#ilr_hide_value'] = TRUE;
    $element['#after_build'][] = '_ilr_disable_textarea_value';
  }
}

/**
 * The #after_build callback for text_with_summary widgets.
 */
function _ilr_disable_textarea_value($form_element, FormStateInterface $form_state) {
  if ($form_element['#ilr_hide_value'] && isset($form_element['value'])) {
    $form_element['value']['#access'] = FALSE;
  }

  return $form_element;
}

/**
 * Implements hook_user_format_name_alter().
 *
 * Display the common name, if available, as the username.
 */
function ilr_user_format_name_alter(&$name, $account) {
  if ($account instanceof User === FALSE) {
    return;
  }

  if (!$account->field_common_name->isEmpty()) {
    $name = $account->field_common_name->value;
  }
}

/**
 * Implements hook_preprocess_HOOK() for `entity_add_list`.
 *
 * Hide some bundles from the 'Add new content' page for blog collections.
 *
 * @see CollectionNew::content().
 */
function ilr_preprocess_entity_add_list__collection_blog_new_node(&$variables) {
  unset($variables['bundles']['certificate']);
  unset($variables['bundles']['course']);
  unset($variables['bundles']['story']);
}

/**
 * Implements hook_preprocess_HOOK() for `entity_add_list`.
 *
 * Hide some bundles from the 'Add new content' page for subsite_blog
 * collections.
 *
 * @see CollectionNew::content().
 */
function ilr_preprocess_entity_add_list__collection_subsite_blog_new_node(&$variables) {
  unset($variables['bundles']['certificate']);
  unset($variables['bundles']['course']);
  unset($variables['bundles']['story']);
}

/**
 * Implements hook_preprocess_HOOK() for `entity_add_list`.
 *
 * Hide some bundles from the 'Add new content' page for content_section
 * collections.
 *
 * @see CollectionNew::content().
 */
function ilr_preprocess_entity_add_list__collection_content_section_new_node(&$variables) {
  unset($variables['bundles']['certificate']);
  unset($variables['bundles']['course']);
  unset($variables['bundles']['story']);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_form_collection_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['body']) || isset($form['field_representative_image'])) {
    $form['ilr_meta'] = [
      '#type' => 'details',
      '#title' => t('Meta'),
      '#group' => 'advanced',
      '#weight' => 0,
      '#optional' => TRUE,
      '#open' => TRUE,
    ];

    if (isset($form['field_representative_image'])) {
      $form['field_representative_image']['#group'] = 'ilr_meta';
    }

    if (isset($form['field_suppress_date_display'])) {
      $form['field_suppress_date_display']['#group'] = 'ilr_meta';
    }

    if (!empty($form['field_download'])) {
      $form['field_download']['#group'] = 'ilr_meta';
    }

    if (!empty($form['field_publication_date'])) {
      $form['field_publication_date']['#group'] = 'ilr_meta';
    }

    if (isset($form['body'])) {
      $form['body']['#group'] = 'ilr_meta';
    }

    if (isset($form['field_section_path'])) {
      $form['field_section_path']['#group'] = 'ilr_meta';
    }

    if (isset($form['behavior_alt_display'])) {
      $form['behavior_alt_display']['#group'] = 'ilr_meta';
    }
  }

  // Enable new revisions by default.
  $form['revision']['#default_value'] = TRUE;
}

/**
 * Implements hook_webform_mailchimp_lists_mergevars_alter().
 *
 * The datelist value should only send a 4 character year string to the MC api,
 * so we transform it here.
 */
function ilr_webform_mailchimp_lists_mergevars_alter(&$mergevars, WebformSubmissionInterface $submission, WebformHandlerInterface $handler) {
  $data = $submission->getData();

  if (!empty($data['degree_year'])) {
    $mergevars['GRADYEAR'] = substr($data['degree_year'], 0, 4);
  }
}

/**
 * Implements hook_pathauto_pattern_alter().
 */
function ilr_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context) {
  // Alter the pattern for page nodes that aren't in the menu.
  if ($pattern->id() === 'page_nodes') {
    $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
    $links = $menu_link_manager->loadLinksByRoute('entity.node.canonical', ['node' => $context['data']['node']->id()]);

    if ($links) {
      // If this page node is in a menu, use a menu-parent based pattern.
      return $pattern->setPattern('[node:menu-link:parent:url:relative]/[node:menu-link:title]');
    }
  }
}

/**
 * Implements hook_collection_pathauto_alias_alter().
 *
 * Updates the alias pattern for story nodes that in a publication_issue
 * collection.
 *
 * Updates the alias pattern for projects in the YTI collection.
 *
 * @see collection_pathauto_pathauto_alias_alter().
 */
function ilr_collection_pathauto_alias_alter(&$alias, array &$context) {
  if ($context['canonical_collection']->bundle() === 'publication_issue' && $context['data']['node']->bundle() === 'story') {
    $alias = str_replace('/story/', '/', $alias);
  }

  // Page nodes have their path patterns altered if they are in a menu (see
  // ilr_pathauto_pattern_alter()). Under certain conditions, like when the menu
  // parent has the collection prefix in it, this can result in a duplicated
  // collection path prefix. We remove that here.
  if ($context['pattern']->id() === 'page_nodes') {
    // Remove the original_alias from the end of the current alias. Whatever is
    // left is the collection path that was prepended in
    // collection_pathauto_pathauto_alias_alter().
    $collection_path = preg_replace("|{$context['original_alias']}$|", '', $alias);

    // Reduce the collection paths to a single value if the current alias starts
    // with two collection paths.
    $deduped_alias = preg_replace("|^{$collection_path}{$collection_path}/|", $collection_path . '/', $alias);
    $alias = $deduped_alias;
  }

  if ($context['canonical_collection']->id() === '57') {
    if (!isset($context['data']['node']) || $context['data']['node']->bundle() != 'project') {
      return;
    }
    // Swap `work` for `project` in the alias.
    $alias = str_replace('/project/', '/work/', $alias);
  }
}

/**
 * Implements hook_preprocess_container__CONTAINER_ID().
 *
 * Update the collection request forms to make more relevant to ILR.
 */
function ilr_preprocess_container__content_entity_collections(&$variables) {
  if (isset($variables['children']['request_form'])) {
    $variables['children']['request_form']['collection_id']['#title'] = t('Request cross-post');
    $variables['children']['request_form']['collection_id']['#description'] = t('Select a collection above and the owner(s) will be notified of your request.');
  }

  if (isset($variables['children']['list']['table'])) {
    foreach ($variables['children']['list']['table']['#rows'] as $collection_item_id => $values) {
      $collection_item = \Drupal::entityTypeManager()->getStorage('collection_item')->load($collection_item_id);

      if (!$collection_item->isCanonical()) {
        $link = $collection_item->toLink(t('Cross-post'));
        $status = ($collection_item->getAttribute('collection-request-uid')) ? t('Pending') : $link;
        $variables['children']['list']['table']['#rows'][$collection_item_id]['canonical'] = $status;
      }
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function ilr_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'collection_item' && $entity->item->entity instanceof VocabularyInterface) {
    $operations = [];
    $operations['add_term'] = [
      'title' => t('Add new'),
      'url' => Url::fromRoute('entity.taxonomy_term.add_form', [
        'taxonomy_vocabulary' =>  $entity->item->entity->id(),
      ]),
      'weight' => 0,
    ];
    return $operations;
  }
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function ilr_preprocess_views_view_field(&$variables) {
  if (empty($variables['row']->_entity) || !$variables['row']->_entity instanceof CollectionItemInterface) {
    return;
  }

  $is_collected_vocabulary = $variables['row']->_entity->item->entity instanceof VocabularyInterface;
  $is_collected_item_field = $variables['field']->realField === 'item__target_id';

  // Link collected vocabularies in collection item listings to the term listing
  // rather than the edit form.
  if ($is_collected_vocabulary && $is_collected_item_field) {
    $variables['output'] = $variables['row']->_entity->item->entity->toLink(null, 'overview-form');
  }
}

/**
 * Implements hook_ENTITY_TYPE_create_access() for entity type 'paragraph'.
 */
function ilr_paragraph_create_access(AccountInterface $account = NULL, array $context = array(), $entity_bundle = NULL) {
  if ($entity_bundle === 'instagram_listing') {
    // We use this restrictive permission to hide the instagram_listing
    // paragraph from most content editors.
    if ($account->hasPermission('administer paragraphs settings')) {
      return AccessResult::allowed()->cachePerPermissions();
    }

    return AccessResult::forbidden()->cachePerPermissions();
  }
}

/**
 * Implements hook_entity_field_access_alter().
 */
function ilr_entity_field_access_alter(array &$grants, array $context) {
  // Add grant access for content owners with 'publish own content` permission.
  if ($context['field_definition']->getTargetEntityTypeId() === 'node' && $context['field_definition']->getName() === 'status' && $context['operation'] === 'edit') {
    if ($context['account']->hasPermission('administer nodes')) {
      return;
    }

    if ($context['items']->getEntity()->getOwnerId() === $context['account']->id()) {
      $grants[':default'] = AccessResult::allowedIfHasPermission($context['account'], 'publish own content');
    }
  }

  // Remove edit access for persona editors field unless user has permission to
  // administer person fields or is the owner if the persona.
  if ($context['field_definition']->getTargetEntityTypeId() === 'persona' && $context['field_definition']->getName() === 'field_editors' && $context['operation'] === 'edit') {
    // Allow access to the editors field if the current user owns the persona.
    if (\Drupal::moduleHandler()->moduleExists('externalauth')) {
      /** @var \Drupal\Core\Field\EntityReferenceFieldItemListInterface $items */
      $items = $context['items'];

      /** @var \Drupal\person\Entity\Persona */
      $persona = $items->getEntity();
      $authmap = \Drupal::service('externalauth.authmap');
      $netid = $authmap->get($context['account']->id(), 'samlauth');

      if ($persona->hasField('field_netid') && $persona->field_netid->value === $netid) {
        return;
      }
    }

    if ($context['account']->hasPermission('administer persons')) {
      return;
    }

    $grants[':default'] = AccessResult::allowedIfHasPermission($context['account'], 'administer person fields and persona types');
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function ilr_collection_item_access(EntityInterface $entity, $op, AccountInterface $account) {
  if ($entity->item->entity instanceof ContentEntityInterface) {
    return AccessResult::neutral();
  }

  // Prevent editing of collection items that collect config entities unless the
  // user can administer collections.
  if ($op === 'update') {
    return AccessResult::forbiddenIf(!$account->hasPermission('administer collections'))->cachePerPermissions();
  }
  // Prevent all users from deleting collection items that collect config
  // entities. These are always added programmatically, so they should also be
  // removed programmatically.
  elseif ($op === 'delete') {
    return AccessResult::forbidden();
  }
}

/**
 * Implements hook_form_alter().
 */
function ilr_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'editor_link_dialog' && isset($form['attributes']['media_library'])) {
    $form['attributes']['media_library']['#value'] = t('Document Library');
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ilr_form_media_confirm_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['entity_usage_delete_warning'])) {
    // Disable the "Delete" button. The entity_usage warning message text is
    // altered in $settings['locale_custom_strings_en'] in settings.php.
    $form['actions']['submit']['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function ilr_module_implements_alter(&$implementations, $hook) {
  // Run ilr_form_editor_link_dialog_alter() after
  // linkit_media_library_form_editor_link_dialog_alter() so we can alter the
  // 'Media Library' button.
  if ($hook === 'form_alter') {
    $group = $implementations['ilr'];
    unset($implementations['ilr']);
    $implementations['ilr'] = $group;
  }
}

/**
 * Implements hook_mail_alter().
 */
function ilr_mail_alter(&$message) {
  // When sending via Campaign Monitor transactional email, this helps with
  // reporting. See
  // https://help.campaignmonitor.com/classic-transactional-emails#group-smtp
  $message['headers']['X-Cmail-GroupName'] = \Drupal::config('system.site')->get('name');

  // Disable Campaign Monitor transactional email tracking features.
  $message['headers']['X-Cmail-TrackOpens'] = 'false';
  $message['headers']['X-Cmail-TrackClicks'] = 'false';
}

/**
 * Implements hook_entity_access().
 *
 * Allow edit access for users with a netid matching the field values of the
 * persona.
 * Check 'edit homepage' permission for node 1.
 *
 * @TODO Remove when owners field is added to persona entities.
 */
function ilr_entity_access(EntityInterface $entity, $op, AccountInterface $account) {
  $access_result = AccessResult::neutral();

  if ($entity instanceof ConfigEntityInterface) {
    return $access_result;
  }

  if (!in_array($op, ['view', 'update'])) {
    return $access_result;
  }

  if ($entity->id() === '1' && $entity->getEntityTypeId() === 'node') {
    return AccessResult::allowedIfHasPermission($account, 'edit homepage');
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  if ($entity->getEntityTypeId() !== 'persona') {
    return $access_result;
  }

  if ($entity->hasField('field_netid') && \Drupal::moduleHandler()->moduleExists('externalauth')) {
    $authmap = \Drupal::service('externalauth.authmap');
    $netid = $authmap->get($account->id(), 'samlauth');

    $access_result = AccessResult::allowedIf(($netid === $entity->field_netid->value))->cachePerUser()->addCacheableDependency($entity);
  }

  if ($entity->hasField('field_editors')) {
    foreach ($entity->field_editors->referencedEntities() as $editor_user) {
      if ($editor_user->id() === $account->id()) {
        $access_result = AccessResult::allowed()->cachePerUser()->addCacheableDependency($entity);
        break;
      }
    }
  }

  return $access_result;
}

/**
 * Implements hook_persona_display_name_alter().
 */
function ilr_persona_display_name_alter(&$display_name, PersonaInterface $persona) {
  if ($persona->hasField('field_display_name_override') && !$persona->field_display_name_override->isEmpty()) {
    $display_name = $persona->field_display_name_override->value;
  }
}
